site_name: WasmDock
site_description: Docker-Native WASM Development Toolkit
site_url: https://hariharanragothaman.github.io/wasmdock/
repo_url: https://github.com/hariharanragothaman/wasmdock
repo_name: hariharanragothaman/wasmdock

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
